/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.City;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CityRecord extends UpdatableRecordImpl<CityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.city.city_id</code>.
     */
    public void setCityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.city.city_id</code>.
     */
    public Integer getCityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.city.city_name</code>.
     */
    public void setCityName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.city.city_name</code>.
     */
    public String getCityName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.city.inhabitants</code>.
     */
    public void setInhabitants(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.city.inhabitants</code>.
     */
    public Integer getInhabitants() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.city.country_id</code>.
     */
    public void setCountryId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.city.country_id</code>.
     */
    public Integer getCountryId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CityRecord
     */
    public CityRecord() {
        super(City.CITY);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    public CityRecord(Integer cityId, String cityName, Integer inhabitants, Integer countryId) {
        super(City.CITY);

        setCityId(cityId);
        setCityName(cityName);
        setInhabitants(inhabitants);
        setCountryId(countryId);
        resetChangedOnNotNull();
    }
}
