/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.Continent;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ContinentRecord extends UpdatableRecordImpl<ContinentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.continent.continent_id</code>.
     */
    public void setContinentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.continent.continent_id</code>.
     */
    public Integer getContinentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.continent.continent_name</code>.
     */
    public void setContinentName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.continent.continent_name</code>.
     */
    public String getContinentName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContinentRecord
     */
    public ContinentRecord() {
        super(Continent.CONTINENT);
    }

    /**
     * Create a detached, initialised ContinentRecord
     */
    public ContinentRecord(Integer continentId, String continentName) {
        super(Continent.CONTINENT);

        setContinentId(continentId);
        setContinentName(continentName);
        resetChangedOnNotNull();
    }
}
