/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.math.BigInteger;

import org.example.jooq.tables.CountryCityInfo;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountryCityInfoRecord extends TableRecordImpl<CountryCityInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.country_city_info.Land</code>.
     */
    public void setLand(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.country_city_info.Land</code>.
     */
    public String getLand() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.country_city_info.Antal Städer</code>.
     */
    public void setAntalStäder(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.country_city_info.Antal Städer</code>.
     */
    public Long getAntalStäder() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.country_city_info.Totala Invånare</code>.
     */
    public void setTotalaInvånare(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.country_city_info.Totala Invånare</code>.
     */
    public BigInteger getTotalaInvånare() {
        return (BigInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryCityInfoRecord
     */
    public CountryCityInfoRecord() {
        super(CountryCityInfo.COUNTRY_CITY_INFO);
    }

    /**
     * Create a detached, initialised CountryCityInfoRecord
     */
    public CountryCityInfoRecord(String land, Long antalStäder, BigInteger totalaInvånare) {
        super(CountryCityInfo.COUNTRY_CITY_INFO);

        setLand(land);
        setAntalStäder(antalStäder);
        setTotalaInvånare(totalaInvånare);
        resetChangedOnNotNull();
    }
}
