/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.time.LocalDate;

import org.example.jooq.tables.Country;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountryRecord extends UpdatableRecordImpl<CountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.country.country_id</code>.
     */
    public void setCountryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.country.country_id</code>.
     */
    public Integer getCountryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.country.country_name</code>.
     */
    public void setCountryName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.country.country_name</code>.
     */
    public String getCountryName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.country.continent_id</code>.
     */
    public void setContinentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.country.continent_id</code>.
     */
    public Integer getContinentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.country.language_code</code>.
     */
    public void setLanguageCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.country.language_code</code>.
     */
    public String getLanguageCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.country.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.country.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.country.national_day</code>.
     */
    public void setNationalDay(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.country.national_day</code>.
     */
    public LocalDate getNationalDay() {
        return (LocalDate) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryRecord
     */
    public CountryRecord() {
        super(Country.COUNTRY);
    }

    /**
     * Create a detached, initialised CountryRecord
     */
    public CountryRecord(Integer countryId, String countryName, Integer continentId, String languageCode, String currencyCode, LocalDate nationalDay) {
        super(Country.COUNTRY);

        setCountryId(countryId);
        setCountryName(countryName);
        setContinentId(continentId);
        setLanguageCode(languageCode);
        setCurrencyCode(currencyCode);
        setNationalDay(nationalDay);
        resetChangedOnNotNull();
    }
}
