/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.EmployeeRestaurant;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeeRestaurantRecord extends UpdatableRecordImpl<EmployeeRestaurantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.employee_restaurant.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.employee_restaurant.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.employee_restaurant.restaurant_id</code>.
     */
    public void setRestaurantId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.employee_restaurant.restaurant_id</code>.
     */
    public Integer getRestaurantId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRestaurantRecord
     */
    public EmployeeRestaurantRecord() {
        super(EmployeeRestaurant.EMPLOYEE_RESTAURANT);
    }

    /**
     * Create a detached, initialised EmployeeRestaurantRecord
     */
    public EmployeeRestaurantRecord(Integer employeeId, Integer restaurantId) {
        super(EmployeeRestaurant.EMPLOYEE_RESTAURANT);

        setEmployeeId(employeeId);
        setRestaurantId(restaurantId);
        resetChangedOnNotNull();
    }
}
