/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.OrganizationMember;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrganizationMemberRecord extends UpdatableRecordImpl<OrganizationMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.Organization_Member.Organization_id</code>.
     */
    public void setOrganizationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.Organization_Member.Organization_id</code>.
     */
    public Long getOrganizationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.Organization_Member.members_id</code>.
     */
    public void setMembersId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.Organization_Member.members_id</code>.
     */
    public Long getMembersId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationMemberRecord
     */
    public OrganizationMemberRecord() {
        super(OrganizationMember.ORGANIZATION_MEMBER);
    }

    /**
     * Create a detached, initialised OrganizationMemberRecord
     */
    public OrganizationMemberRecord(Long organizationId, Long membersId) {
        super(OrganizationMember.ORGANIZATION_MEMBER);

        setOrganizationId(organizationId);
        setMembersId(membersId);
        resetChangedOnNotNull();
    }
}
