/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.RestaurantEmployeeCount;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestaurantEmployeeCountRecord extends TableRecordImpl<RestaurantEmployeeCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.restaurant_employee_count.Restaurang</code>.
     */
    public void setRestaurang(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.restaurant_employee_count.Restaurang</code>.
     */
    public String getRestaurang() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.restaurant_employee_count.Antal Anställda</code>.
     */
    public void setAntalAnställda(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.restaurant_employee_count.Antal Anställda</code>.
     */
    public Long getAntalAnställda() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestaurantEmployeeCountRecord
     */
    public RestaurantEmployeeCountRecord() {
        super(RestaurantEmployeeCount.RESTAURANT_EMPLOYEE_COUNT);
    }

    /**
     * Create a detached, initialised RestaurantEmployeeCountRecord
     */
    public RestaurantEmployeeCountRecord(String restaurang, Long antalAnställda) {
        super(RestaurantEmployeeCount.RESTAURANT_EMPLOYEE_COUNT);

        setRestaurang(restaurang);
        setAntalAnställda(antalAnställda);
        resetChangedOnNotNull();
    }
}
