/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.math.BigDecimal;

import org.example.jooq.tables.Restaurant;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestaurantRecord extends UpdatableRecordImpl<RestaurantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.restaurant.restaurant_id</code>.
     */
    public void setRestaurantId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.restaurant.restaurant_id</code>.
     */
    public Integer getRestaurantId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.restaurant.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.restaurant.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.restaurant.employee_count</code>.
     */
    public void setEmployeeCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.restaurant.employee_count</code>.
     */
    public Integer getEmployeeCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.restaurant.rating</code>.
     */
    public void setRating(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.restaurant.rating</code>.
     */
    public BigDecimal getRating() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>test.restaurant.city_id</code>.
     */
    public void setCityId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.restaurant.city_id</code>.
     */
    public Integer getCityId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestaurantRecord
     */
    public RestaurantRecord() {
        super(Restaurant.RESTAURANT);
    }

    /**
     * Create a detached, initialised RestaurantRecord
     */
    public RestaurantRecord(Integer restaurantId, String name, Integer employeeCount, BigDecimal rating, Integer cityId) {
        super(Restaurant.RESTAURANT);

        setRestaurantId(restaurantId);
        setName(name);
        setEmployeeCount(employeeCount);
        setRating(rating);
        setCityId(cityId);
        resetChangedOnNotNull();
    }
}
