/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import org.example.jooq.tables.TableName;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TableNameRecord extends TableRecordImpl<TableNameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.table_name.column_name</code>.
     */
    public void setColumnName(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.table_name.column_name</code>.
     */
    public Integer getColumnName() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableNameRecord
     */
    public TableNameRecord() {
        super(TableName.TABLE_NAME);
    }

    /**
     * Create a detached, initialised TableNameRecord
     */
    public TableNameRecord(Integer columnName) {
        super(TableName.TABLE_NAME);

        setColumnName(columnName);
        resetChangedOnNotNull();
    }
}
