/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.City;
import org.example.jooq.tables.Country;
import org.example.jooq.tables.EmployeeRestaurant;
import org.example.jooq.tables.Restaurant;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RESTAURANT_CITY_ID = Internal.createIndex(DSL.name("city_id"), Restaurant.RESTAURANT, new OrderField[] { Restaurant.RESTAURANT.CITY_ID }, false);
    public static final Index COUNTRY_CONTINENT_ID = Internal.createIndex(DSL.name("continent_id"), Country.COUNTRY, new OrderField[] { Country.COUNTRY.CONTINENT_ID }, false);
    public static final Index CITY_COUNTRY_ID = Internal.createIndex(DSL.name("country_id"), City.CITY, new OrderField[] { City.CITY.COUNTRY_ID }, false);
    public static final Index EMPLOYEE_RESTAURANT_RESTAURANT_ID = Internal.createIndex(DSL.name("restaurant_id"), EmployeeRestaurant.EMPLOYEE_RESTAURANT, new OrderField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.RESTAURANT_ID }, false);
}
