/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.City;
import org.example.jooq.tables.Continent;
import org.example.jooq.tables.Country;
import org.example.jooq.tables.Employee;
import org.example.jooq.tables.EmployeeRestaurant;
import org.example.jooq.tables.Member;
import org.example.jooq.tables.Organization;
import org.example.jooq.tables.OrganizationMember;
import org.example.jooq.tables.Restaurant;
import org.example.jooq.tables.records.CityRecord;
import org.example.jooq.tables.records.ContinentRecord;
import org.example.jooq.tables.records.CountryRecord;
import org.example.jooq.tables.records.EmployeeRecord;
import org.example.jooq.tables.records.EmployeeRestaurantRecord;
import org.example.jooq.tables.records.MemberRecord;
import org.example.jooq.tables.records.OrganizationMemberRecord;
import org.example.jooq.tables.records.OrganizationRecord;
import org.example.jooq.tables.records.RestaurantRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CityRecord> KEY_CITY_PRIMARY = Internal.createUniqueKey(City.CITY, DSL.name("KEY_city_PRIMARY"), new TableField[] { City.CITY.CITY_ID }, true);
    public static final UniqueKey<ContinentRecord> KEY_CONTINENT_PRIMARY = Internal.createUniqueKey(Continent.CONTINENT, DSL.name("KEY_continent_PRIMARY"), new TableField[] { Continent.CONTINENT.CONTINENT_ID }, true);
    public static final UniqueKey<CountryRecord> KEY_COUNTRY_PRIMARY = Internal.createUniqueKey(Country.COUNTRY, DSL.name("KEY_country_PRIMARY"), new TableField[] { Country.COUNTRY.COUNTRY_ID }, true);
    public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("KEY_employee_PRIMARY"), new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
    public static final UniqueKey<EmployeeRestaurantRecord> KEY_EMPLOYEE_RESTAURANT_PRIMARY = Internal.createUniqueKey(EmployeeRestaurant.EMPLOYEE_RESTAURANT, DSL.name("KEY_employee_restaurant_PRIMARY"), new TableField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.EMPLOYEE_ID, EmployeeRestaurant.EMPLOYEE_RESTAURANT.RESTAURANT_ID }, true);
    public static final UniqueKey<MemberRecord> KEY_MEMBER_PRIMARY = Internal.createUniqueKey(Member.MEMBER, DSL.name("KEY_Member_PRIMARY"), new TableField[] { Member.MEMBER.ID }, true);
    public static final UniqueKey<OrganizationRecord> KEY_ORGANIZATION_PRIMARY = Internal.createUniqueKey(Organization.ORGANIZATION, DSL.name("KEY_Organization_PRIMARY"), new TableField[] { Organization.ORGANIZATION.ID }, true);
    public static final UniqueKey<OrganizationMemberRecord> KEY_ORGANIZATION_MEMBER_PRIMARY = Internal.createUniqueKey(OrganizationMember.ORGANIZATION_MEMBER, DSL.name("KEY_Organization_Member_PRIMARY"), new TableField[] { OrganizationMember.ORGANIZATION_MEMBER.ORGANIZATION_ID, OrganizationMember.ORGANIZATION_MEMBER.MEMBERS_ID }, true);
    public static final UniqueKey<RestaurantRecord> KEY_RESTAURANT_PRIMARY = Internal.createUniqueKey(Restaurant.RESTAURANT, DSL.name("KEY_restaurant_PRIMARY"), new TableField[] { Restaurant.RESTAURANT.RESTAURANT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CityRecord, CountryRecord> CITY_IBFK_1 = Internal.createForeignKey(City.CITY, DSL.name("city_ibfk_1"), new TableField[] { City.CITY.COUNTRY_ID }, Keys.KEY_COUNTRY_PRIMARY, new TableField[] { Country.COUNTRY.COUNTRY_ID }, true);
    public static final ForeignKey<CityRecord, CountryRecord> FKRPD7J1P7YXR784ADKX4PYEPBA = Internal.createForeignKey(City.CITY, DSL.name("FKrpd7j1p7yxr784adkx4pyepba"), new TableField[] { City.CITY.COUNTRY_ID }, Keys.KEY_COUNTRY_PRIMARY, new TableField[] { Country.COUNTRY.COUNTRY_ID }, true);
    public static final ForeignKey<CountryRecord, ContinentRecord> COUNTRY_IBFK_1 = Internal.createForeignKey(Country.COUNTRY, DSL.name("country_ibfk_1"), new TableField[] { Country.COUNTRY.CONTINENT_ID }, Keys.KEY_CONTINENT_PRIMARY, new TableField[] { Continent.CONTINENT.CONTINENT_ID }, true);
    public static final ForeignKey<CountryRecord, ContinentRecord> FKPYMFSGRL32DY3GTL9R7RYKKJG = Internal.createForeignKey(Country.COUNTRY, DSL.name("FKpymfsgrl32dy3gtl9r7rykkjg"), new TableField[] { Country.COUNTRY.CONTINENT_ID }, Keys.KEY_CONTINENT_PRIMARY, new TableField[] { Continent.CONTINENT.CONTINENT_ID }, true);
    public static final ForeignKey<EmployeeRestaurantRecord, EmployeeRecord> EMPLOYEE_RESTAURANT_IBFK_1 = Internal.createForeignKey(EmployeeRestaurant.EMPLOYEE_RESTAURANT, DSL.name("employee_restaurant_ibfk_1"), new TableField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.EMPLOYEE_ID }, Keys.KEY_EMPLOYEE_PRIMARY, new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
    public static final ForeignKey<EmployeeRestaurantRecord, RestaurantRecord> EMPLOYEE_RESTAURANT_IBFK_2 = Internal.createForeignKey(EmployeeRestaurant.EMPLOYEE_RESTAURANT, DSL.name("employee_restaurant_ibfk_2"), new TableField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.RESTAURANT_ID }, Keys.KEY_RESTAURANT_PRIMARY, new TableField[] { Restaurant.RESTAURANT.RESTAURANT_ID }, true);
    public static final ForeignKey<EmployeeRestaurantRecord, EmployeeRecord> FKK3N4AQDUXDBJ5YBQLLJYP9ES7 = Internal.createForeignKey(EmployeeRestaurant.EMPLOYEE_RESTAURANT, DSL.name("FKk3n4aqduxdbj5ybqlljyp9es7"), new TableField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.EMPLOYEE_ID }, Keys.KEY_EMPLOYEE_PRIMARY, new TableField[] { Employee.EMPLOYEE.EMPLOYEE_ID }, true);
    public static final ForeignKey<EmployeeRestaurantRecord, RestaurantRecord> FKMRRUKMHMYSLPV2QHF2BCWCGM6 = Internal.createForeignKey(EmployeeRestaurant.EMPLOYEE_RESTAURANT, DSL.name("FKmrrukmhmyslpv2qhf2bcwcgm6"), new TableField[] { EmployeeRestaurant.EMPLOYEE_RESTAURANT.RESTAURANT_ID }, Keys.KEY_RESTAURANT_PRIMARY, new TableField[] { Restaurant.RESTAURANT.RESTAURANT_ID }, true);
    public static final ForeignKey<OrganizationMemberRecord, OrganizationRecord> FK3OU05GN1LQHE1WJ992DNNCF3W = Internal.createForeignKey(OrganizationMember.ORGANIZATION_MEMBER, DSL.name("FK3ou05gn1lqhe1wj992dnncf3w"), new TableField[] { OrganizationMember.ORGANIZATION_MEMBER.ORGANIZATION_ID }, Keys.KEY_ORGANIZATION_PRIMARY, new TableField[] { Organization.ORGANIZATION.ID }, true);
    public static final ForeignKey<OrganizationMemberRecord, MemberRecord> FK99B1072T8R62TWT7A8QRXAHT7 = Internal.createForeignKey(OrganizationMember.ORGANIZATION_MEMBER, DSL.name("FK99b1072t8r62twt7a8qrxaht7"), new TableField[] { OrganizationMember.ORGANIZATION_MEMBER.MEMBERS_ID }, Keys.KEY_MEMBER_PRIMARY, new TableField[] { Member.MEMBER.ID }, true);
    public static final ForeignKey<RestaurantRecord, CityRecord> FKL968D8D7966YYMVSXTDSNI1VW = Internal.createForeignKey(Restaurant.RESTAURANT, DSL.name("FKl968d8d7966yymvsxtdsni1vw"), new TableField[] { Restaurant.RESTAURANT.CITY_ID }, Keys.KEY_CITY_PRIMARY, new TableField[] { City.CITY.CITY_ID }, true);
    public static final ForeignKey<RestaurantRecord, CityRecord> RESTAURANT_IBFK_1 = Internal.createForeignKey(Restaurant.RESTAURANT, DSL.name("restaurant_ibfk_1"), new TableField[] { Restaurant.RESTAURANT.CITY_ID }, Keys.KEY_CITY_PRIMARY, new TableField[] { City.CITY.CITY_ID }, true);
}
