/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.City;
import org.example.jooq.tables.Continent;
import org.example.jooq.tables.Country;
import org.example.jooq.tables.CountryCityInfo;
import org.example.jooq.tables.Employee;
import org.example.jooq.tables.EmployeeRestaurant;
import org.example.jooq.tables.Member;
import org.example.jooq.tables.Organization;
import org.example.jooq.tables.OrganizationMember;
import org.example.jooq.tables.Restaurant;
import org.example.jooq.tables.RestaurantEmployeeCount;
import org.example.jooq.tables.TableName;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>test.city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>test.continent</code>.
     */
    public static final Continent CONTINENT = Continent.CONTINENT;

    /**
     * The table <code>test.country</code>.
     */
    public static final Country COUNTRY = Country.COUNTRY;

    /**
     * VIEW
     */
    public static final CountryCityInfo COUNTRY_CITY_INFO = CountryCityInfo.COUNTRY_CITY_INFO;

    /**
     * The table <code>test.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>test.employee_restaurant</code>.
     */
    public static final EmployeeRestaurant EMPLOYEE_RESTAURANT = EmployeeRestaurant.EMPLOYEE_RESTAURANT;

    /**
     * The table <code>test.Member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>test.Organization</code>.
     */
    public static final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>test.Organization_Member</code>.
     */
    public static final OrganizationMember ORGANIZATION_MEMBER = OrganizationMember.ORGANIZATION_MEMBER;

    /**
     * The table <code>test.restaurant</code>.
     */
    public static final Restaurant RESTAURANT = Restaurant.RESTAURANT;

    /**
     * VIEW
     */
    public static final RestaurantEmployeeCount RESTAURANT_EMPLOYEE_COUNT = RestaurantEmployeeCount.RESTAURANT_EMPLOYEE_COUNT;

    /**
     * The table <code>test.table_name</code>.
     */
    public static final TableName TABLE_NAME = TableName.TABLE_NAME;
}
