/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import java.util.Arrays;
import java.util.List;

import org.example.jooq.tables.City;
import org.example.jooq.tables.Continent;
import org.example.jooq.tables.Country;
import org.example.jooq.tables.CountryCityInfo;
import org.example.jooq.tables.Employee;
import org.example.jooq.tables.EmployeeRestaurant;
import org.example.jooq.tables.Member;
import org.example.jooq.tables.Organization;
import org.example.jooq.tables.OrganizationMember;
import org.example.jooq.tables.Restaurant;
import org.example.jooq.tables.RestaurantEmployeeCount;
import org.example.jooq.tables.TableName;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>test.continent</code>.
     */
    public final Continent CONTINENT = Continent.CONTINENT;

    /**
     * The table <code>test.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * VIEW
     */
    public final CountryCityInfo COUNTRY_CITY_INFO = CountryCityInfo.COUNTRY_CITY_INFO;

    /**
     * The table <code>test.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>test.employee_restaurant</code>.
     */
    public final EmployeeRestaurant EMPLOYEE_RESTAURANT = EmployeeRestaurant.EMPLOYEE_RESTAURANT;

    /**
     * The table <code>test.Member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * The table <code>test.Organization</code>.
     */
    public final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>test.Organization_Member</code>.
     */
    public final OrganizationMember ORGANIZATION_MEMBER = OrganizationMember.ORGANIZATION_MEMBER;

    /**
     * The table <code>test.restaurant</code>.
     */
    public final Restaurant RESTAURANT = Restaurant.RESTAURANT;

    /**
     * VIEW
     */
    public final RestaurantEmployeeCount RESTAURANT_EMPLOYEE_COUNT = RestaurantEmployeeCount.RESTAURANT_EMPLOYEE_COUNT;

    /**
     * The table <code>test.table_name</code>.
     */
    public final TableName TABLE_NAME = TableName.TABLE_NAME;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            City.CITY,
            Continent.CONTINENT,
            Country.COUNTRY,
            CountryCityInfo.COUNTRY_CITY_INFO,
            Employee.EMPLOYEE,
            EmployeeRestaurant.EMPLOYEE_RESTAURANT,
            Member.MEMBER,
            Organization.ORGANIZATION,
            OrganizationMember.ORGANIZATION_MEMBER,
            Restaurant.RESTAURANT,
            RestaurantEmployeeCount.RESTAURANT_EMPLOYEE_COUNT,
            TableName.TABLE_NAME
        );
    }
}
