/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.jooq.Indexes;
import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Country.CountryPath;
import org.example.jooq.tables.Restaurant.RestaurantPath;
import org.example.jooq.tables.records.CityRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class City extends TableImpl<CityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.city</code>
     */
    public static final City CITY = new City();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CityRecord> getRecordType() {
        return CityRecord.class;
    }

    /**
     * The column <code>test.city.city_id</code>.
     */
    public final TableField<CityRecord, Integer> CITY_ID = createField(DSL.name("city_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.city.city_name</code>.
     */
    public final TableField<CityRecord, String> CITY_NAME = createField(DSL.name("city_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.city.inhabitants</code>.
     */
    public final TableField<CityRecord, Integer> INHABITANTS = createField(DSL.name("inhabitants"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.city.country_id</code>.
     */
    public final TableField<CityRecord, Integer> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.INTEGER, this, "");

    private City(Name alias, Table<CityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private City(Name alias, Table<CityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.city</code> table reference
     */
    public City(String alias) {
        this(DSL.name(alias), CITY);
    }

    /**
     * Create an aliased <code>test.city</code> table reference
     */
    public City(Name alias) {
        this(alias, CITY);
    }

    /**
     * Create a <code>test.city</code> table reference
     */
    public City() {
        this(DSL.name("city"), null);
    }

    public <O extends Record> City(Table<O> path, ForeignKey<O, CityRecord> childPath, InverseForeignKey<O, CityRecord> parentPath) {
        super(path, childPath, parentPath, CITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CityPath extends City implements Path<CityRecord> {
        public <O extends Record> CityPath(Table<O> path, ForeignKey<O, CityRecord> childPath, InverseForeignKey<O, CityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CityPath(Name alias, Table<CityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CityPath as(String alias) {
            return new CityPath(DSL.name(alias), this);
        }

        @Override
        public CityPath as(Name alias) {
            return new CityPath(alias, this);
        }

        @Override
        public CityPath as(Table<?> alias) {
            return new CityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CITY_COUNTRY_ID);
    }

    @Override
    public Identity<CityRecord, Integer> getIdentity() {
        return (Identity<CityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CityRecord> getPrimaryKey() {
        return Keys.KEY_CITY_PRIMARY;
    }

    @Override
    public List<ForeignKey<CityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CITY_IBFK_1, Keys.FKRPD7J1P7YXR784ADKX4PYEPBA);
    }

    private transient CountryPath _cityIbfk_1;

    /**
     * Get the implicit join path to the <code>test.country</code> table, via
     * the <code>city_ibfk_1</code> key.
     */
    public CountryPath cityIbfk_1() {
        if (_cityIbfk_1 == null)
            _cityIbfk_1 = new CountryPath(this, Keys.CITY_IBFK_1, null);

        return _cityIbfk_1;
    }

    private transient CountryPath _fkrpd7j1p7yxr784adkx4pyepba;

    /**
     * Get the implicit join path to the <code>test.country</code> table, via
     * the <code>FKrpd7j1p7yxr784adkx4pyepba</code> key.
     */
    public CountryPath fkrpd7j1p7yxr784adkx4pyepba() {
        if (_fkrpd7j1p7yxr784adkx4pyepba == null)
            _fkrpd7j1p7yxr784adkx4pyepba = new CountryPath(this, Keys.FKRPD7J1P7YXR784ADKX4PYEPBA, null);

        return _fkrpd7j1p7yxr784adkx4pyepba;
    }

    private transient RestaurantPath _fkl968d8d7966yymvsxtdsni1vw;

    /**
     * Get the implicit to-many join path to the <code>test.restaurant</code>
     * table, via the <code>FKl968d8d7966yymvsxtdsni1vw</code> key
     */
    public RestaurantPath fkl968d8d7966yymvsxtdsni1vw() {
        if (_fkl968d8d7966yymvsxtdsni1vw == null)
            _fkl968d8d7966yymvsxtdsni1vw = new RestaurantPath(this, null, Keys.FKL968D8D7966YYMVSXTDSNI1VW.getInverseKey());

        return _fkl968d8d7966yymvsxtdsni1vw;
    }

    private transient RestaurantPath _restaurantIbfk_1;

    /**
     * Get the implicit to-many join path to the <code>test.restaurant</code>
     * table, via the <code>restaurant_ibfk_1</code> key
     */
    public RestaurantPath restaurantIbfk_1() {
        if (_restaurantIbfk_1 == null)
            _restaurantIbfk_1 = new RestaurantPath(this, null, Keys.RESTAURANT_IBFK_1.getInverseKey());

        return _restaurantIbfk_1;
    }

    @Override
    public City as(String alias) {
        return new City(DSL.name(alias), this);
    }

    @Override
    public City as(Name alias) {
        return new City(alias, this);
    }

    @Override
    public City as(Table<?> alias) {
        return new City(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public City rename(String name) {
        return new City(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public City rename(Name name) {
        return new City(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public City rename(Table<?> name) {
        return new City(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City where(Condition condition) {
        return new City(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public City where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public City where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public City where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public City where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public City whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
