/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Country.CountryPath;
import org.example.jooq.tables.records.ContinentRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Continent extends TableImpl<ContinentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.continent</code>
     */
    public static final Continent CONTINENT = new Continent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContinentRecord> getRecordType() {
        return ContinentRecord.class;
    }

    /**
     * The column <code>test.continent.continent_id</code>.
     */
    public final TableField<ContinentRecord, Integer> CONTINENT_ID = createField(DSL.name("continent_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.continent.continent_name</code>.
     */
    public final TableField<ContinentRecord, String> CONTINENT_NAME = createField(DSL.name("continent_name"), SQLDataType.VARCHAR(255), this, "");

    private Continent(Name alias, Table<ContinentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Continent(Name alias, Table<ContinentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.continent</code> table reference
     */
    public Continent(String alias) {
        this(DSL.name(alias), CONTINENT);
    }

    /**
     * Create an aliased <code>test.continent</code> table reference
     */
    public Continent(Name alias) {
        this(alias, CONTINENT);
    }

    /**
     * Create a <code>test.continent</code> table reference
     */
    public Continent() {
        this(DSL.name("continent"), null);
    }

    public <O extends Record> Continent(Table<O> path, ForeignKey<O, ContinentRecord> childPath, InverseForeignKey<O, ContinentRecord> parentPath) {
        super(path, childPath, parentPath, CONTINENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ContinentPath extends Continent implements Path<ContinentRecord> {
        public <O extends Record> ContinentPath(Table<O> path, ForeignKey<O, ContinentRecord> childPath, InverseForeignKey<O, ContinentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ContinentPath(Name alias, Table<ContinentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ContinentPath as(String alias) {
            return new ContinentPath(DSL.name(alias), this);
        }

        @Override
        public ContinentPath as(Name alias) {
            return new ContinentPath(alias, this);
        }

        @Override
        public ContinentPath as(Table<?> alias) {
            return new ContinentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public Identity<ContinentRecord, Integer> getIdentity() {
        return (Identity<ContinentRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ContinentRecord> getPrimaryKey() {
        return Keys.KEY_CONTINENT_PRIMARY;
    }

    private transient CountryPath _countryIbfk_1;

    /**
     * Get the implicit to-many join path to the <code>test.country</code>
     * table, via the <code>country_ibfk_1</code> key
     */
    public CountryPath countryIbfk_1() {
        if (_countryIbfk_1 == null)
            _countryIbfk_1 = new CountryPath(this, null, Keys.COUNTRY_IBFK_1.getInverseKey());

        return _countryIbfk_1;
    }

    private transient CountryPath _fkpymfsgrl32dy3gtl9r7rykkjg;

    /**
     * Get the implicit to-many join path to the <code>test.country</code>
     * table, via the <code>FKpymfsgrl32dy3gtl9r7rykkjg</code> key
     */
    public CountryPath fkpymfsgrl32dy3gtl9r7rykkjg() {
        if (_fkpymfsgrl32dy3gtl9r7rykkjg == null)
            _fkpymfsgrl32dy3gtl9r7rykkjg = new CountryPath(this, null, Keys.FKPYMFSGRL32DY3GTL9R7RYKKJG.getInverseKey());

        return _fkpymfsgrl32dy3gtl9r7rykkjg;
    }

    @Override
    public Continent as(String alias) {
        return new Continent(DSL.name(alias), this);
    }

    @Override
    public Continent as(Name alias) {
        return new Continent(alias, this);
    }

    @Override
    public Continent as(Table<?> alias) {
        return new Continent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Continent rename(String name) {
        return new Continent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Continent rename(Name name) {
        return new Continent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Continent rename(Table<?> name) {
        return new Continent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent where(Condition condition) {
        return new Continent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Continent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Continent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Continent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Continent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Continent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
