/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.math.BigInteger;
import java.util.Collection;

import org.example.jooq.Test;
import org.example.jooq.tables.records.CountryCityInfoRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CountryCityInfo extends TableImpl<CountryCityInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.country_city_info</code>
     */
    public static final CountryCityInfo COUNTRY_CITY_INFO = new CountryCityInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountryCityInfoRecord> getRecordType() {
        return CountryCityInfoRecord.class;
    }

    /**
     * The column <code>test.country_city_info.Land</code>.
     */
    public final TableField<CountryCityInfoRecord, String> LAND = createField(DSL.name("Land"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.country_city_info.Antal Städer</code>.
     */
    public final TableField<CountryCityInfoRecord, Long> ANTAL_STÄDER = createField(DSL.name("Antal Städer"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>test.country_city_info.Totala Invånare</code>.
     */
    public final TableField<CountryCityInfoRecord, BigInteger> TOTALA_INVÅNARE = createField(DSL.name("Totala Invånare"), SQLDataType.DECIMAL_INTEGER(32), this, "");

    private CountryCityInfo(Name alias, Table<CountryCityInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CountryCityInfo(Name alias, Table<CountryCityInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `country_city_info` as select `c`.`country_name` AS `Land`,count(`test`.`city`.`city_id`) AS `Antal Städer`,sum(`test`.`city`.`inhabitants`) AS `Totala Invånare` from (`test`.`country` `c` join `test`.`city` on((`c`.`country_id` = `test`.`city`.`country_id`))) group by `c`.`country_name`"), where);
    }

    /**
     * Create an aliased <code>test.country_city_info</code> table reference
     */
    public CountryCityInfo(String alias) {
        this(DSL.name(alias), COUNTRY_CITY_INFO);
    }

    /**
     * Create an aliased <code>test.country_city_info</code> table reference
     */
    public CountryCityInfo(Name alias) {
        this(alias, COUNTRY_CITY_INFO);
    }

    /**
     * Create a <code>test.country_city_info</code> table reference
     */
    public CountryCityInfo() {
        this(DSL.name("country_city_info"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public CountryCityInfo as(String alias) {
        return new CountryCityInfo(DSL.name(alias), this);
    }

    @Override
    public CountryCityInfo as(Name alias) {
        return new CountryCityInfo(alias, this);
    }

    @Override
    public CountryCityInfo as(Table<?> alias) {
        return new CountryCityInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CountryCityInfo rename(String name) {
        return new CountryCityInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CountryCityInfo rename(Name name) {
        return new CountryCityInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CountryCityInfo rename(Table<?> name) {
        return new CountryCityInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo where(Condition condition) {
        return new CountryCityInfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CountryCityInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CountryCityInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CountryCityInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CountryCityInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CountryCityInfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
