/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.jooq.Indexes;
import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.City.CityPath;
import org.example.jooq.tables.Continent.ContinentPath;
import org.example.jooq.tables.records.CountryRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Country extends TableImpl<CountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.country</code>
     */
    public static final Country COUNTRY = new Country();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountryRecord> getRecordType() {
        return CountryRecord.class;
    }

    /**
     * The column <code>test.country.country_id</code>.
     */
    public final TableField<CountryRecord, Integer> COUNTRY_ID = createField(DSL.name("country_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.country.country_name</code>.
     */
    public final TableField<CountryRecord, String> COUNTRY_NAME = createField(DSL.name("country_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.country.continent_id</code>.
     */
    public final TableField<CountryRecord, Integer> CONTINENT_ID = createField(DSL.name("continent_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.country.language_code</code>.
     */
    public final TableField<CountryRecord, String> LANGUAGE_CODE = createField(DSL.name("language_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.country.currency_code</code>.
     */
    public final TableField<CountryRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.country.national_day</code>.
     */
    public final TableField<CountryRecord, LocalDate> NATIONAL_DAY = createField(DSL.name("national_day"), SQLDataType.LOCALDATE, this, "");

    private Country(Name alias, Table<CountryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Country(Name alias, Table<CountryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.country</code> table reference
     */
    public Country(String alias) {
        this(DSL.name(alias), COUNTRY);
    }

    /**
     * Create an aliased <code>test.country</code> table reference
     */
    public Country(Name alias) {
        this(alias, COUNTRY);
    }

    /**
     * Create a <code>test.country</code> table reference
     */
    public Country() {
        this(DSL.name("country"), null);
    }

    public <O extends Record> Country(Table<O> path, ForeignKey<O, CountryRecord> childPath, InverseForeignKey<O, CountryRecord> parentPath) {
        super(path, childPath, parentPath, COUNTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CountryPath extends Country implements Path<CountryRecord> {
        public <O extends Record> CountryPath(Table<O> path, ForeignKey<O, CountryRecord> childPath, InverseForeignKey<O, CountryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CountryPath(Name alias, Table<CountryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CountryPath as(String alias) {
            return new CountryPath(DSL.name(alias), this);
        }

        @Override
        public CountryPath as(Name alias) {
            return new CountryPath(alias, this);
        }

        @Override
        public CountryPath as(Table<?> alias) {
            return new CountryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.COUNTRY_CONTINENT_ID);
    }

    @Override
    public Identity<CountryRecord, Integer> getIdentity() {
        return (Identity<CountryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CountryRecord> getPrimaryKey() {
        return Keys.KEY_COUNTRY_PRIMARY;
    }

    @Override
    public List<ForeignKey<CountryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COUNTRY_IBFK_1, Keys.FKPYMFSGRL32DY3GTL9R7RYKKJG);
    }

    private transient ContinentPath _countryIbfk_1;

    /**
     * Get the implicit join path to the <code>test.continent</code> table, via
     * the <code>country_ibfk_1</code> key.
     */
    public ContinentPath countryIbfk_1() {
        if (_countryIbfk_1 == null)
            _countryIbfk_1 = new ContinentPath(this, Keys.COUNTRY_IBFK_1, null);

        return _countryIbfk_1;
    }

    private transient ContinentPath _fkpymfsgrl32dy3gtl9r7rykkjg;

    /**
     * Get the implicit join path to the <code>test.continent</code> table, via
     * the <code>FKpymfsgrl32dy3gtl9r7rykkjg</code> key.
     */
    public ContinentPath fkpymfsgrl32dy3gtl9r7rykkjg() {
        if (_fkpymfsgrl32dy3gtl9r7rykkjg == null)
            _fkpymfsgrl32dy3gtl9r7rykkjg = new ContinentPath(this, Keys.FKPYMFSGRL32DY3GTL9R7RYKKJG, null);

        return _fkpymfsgrl32dy3gtl9r7rykkjg;
    }

    private transient CityPath _cityIbfk_1;

    /**
     * Get the implicit to-many join path to the <code>test.city</code> table,
     * via the <code>city_ibfk_1</code> key
     */
    public CityPath cityIbfk_1() {
        if (_cityIbfk_1 == null)
            _cityIbfk_1 = new CityPath(this, null, Keys.CITY_IBFK_1.getInverseKey());

        return _cityIbfk_1;
    }

    private transient CityPath _fkrpd7j1p7yxr784adkx4pyepba;

    /**
     * Get the implicit to-many join path to the <code>test.city</code> table,
     * via the <code>FKrpd7j1p7yxr784adkx4pyepba</code> key
     */
    public CityPath fkrpd7j1p7yxr784adkx4pyepba() {
        if (_fkrpd7j1p7yxr784adkx4pyepba == null)
            _fkrpd7j1p7yxr784adkx4pyepba = new CityPath(this, null, Keys.FKRPD7J1P7YXR784ADKX4PYEPBA.getInverseKey());

        return _fkrpd7j1p7yxr784adkx4pyepba;
    }

    @Override
    public Country as(String alias) {
        return new Country(DSL.name(alias), this);
    }

    @Override
    public Country as(Name alias) {
        return new Country(alias, this);
    }

    @Override
    public Country as(Table<?> alias) {
        return new Country(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Country rename(String name) {
        return new Country(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Country rename(Name name) {
        return new Country(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Country rename(Table<?> name) {
        return new Country(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country where(Condition condition) {
        return new Country(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Country where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Country where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Country where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Country where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Country whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
