/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.jooq.Indexes;
import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Employee.EmployeePath;
import org.example.jooq.tables.Restaurant.RestaurantPath;
import org.example.jooq.tables.records.EmployeeRestaurantRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeeRestaurant extends TableImpl<EmployeeRestaurantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.employee_restaurant</code>
     */
    public static final EmployeeRestaurant EMPLOYEE_RESTAURANT = new EmployeeRestaurant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeRestaurantRecord> getRecordType() {
        return EmployeeRestaurantRecord.class;
    }

    /**
     * The column <code>test.employee_restaurant.employee_id</code>.
     */
    public final TableField<EmployeeRestaurantRecord, Integer> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.employee_restaurant.restaurant_id</code>.
     */
    public final TableField<EmployeeRestaurantRecord, Integer> RESTAURANT_ID = createField(DSL.name("restaurant_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private EmployeeRestaurant(Name alias, Table<EmployeeRestaurantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmployeeRestaurant(Name alias, Table<EmployeeRestaurantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.employee_restaurant</code> table reference
     */
    public EmployeeRestaurant(String alias) {
        this(DSL.name(alias), EMPLOYEE_RESTAURANT);
    }

    /**
     * Create an aliased <code>test.employee_restaurant</code> table reference
     */
    public EmployeeRestaurant(Name alias) {
        this(alias, EMPLOYEE_RESTAURANT);
    }

    /**
     * Create a <code>test.employee_restaurant</code> table reference
     */
    public EmployeeRestaurant() {
        this(DSL.name("employee_restaurant"), null);
    }

    public <O extends Record> EmployeeRestaurant(Table<O> path, ForeignKey<O, EmployeeRestaurantRecord> childPath, InverseForeignKey<O, EmployeeRestaurantRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEE_RESTAURANT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeeRestaurantPath extends EmployeeRestaurant implements Path<EmployeeRestaurantRecord> {
        public <O extends Record> EmployeeRestaurantPath(Table<O> path, ForeignKey<O, EmployeeRestaurantRecord> childPath, InverseForeignKey<O, EmployeeRestaurantRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeeRestaurantPath(Name alias, Table<EmployeeRestaurantRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeeRestaurantPath as(String alias) {
            return new EmployeeRestaurantPath(DSL.name(alias), this);
        }

        @Override
        public EmployeeRestaurantPath as(Name alias) {
            return new EmployeeRestaurantPath(alias, this);
        }

        @Override
        public EmployeeRestaurantPath as(Table<?> alias) {
            return new EmployeeRestaurantPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.EMPLOYEE_RESTAURANT_RESTAURANT_ID);
    }

    @Override
    public UniqueKey<EmployeeRestaurantRecord> getPrimaryKey() {
        return Keys.KEY_EMPLOYEE_RESTAURANT_PRIMARY;
    }

    @Override
    public List<ForeignKey<EmployeeRestaurantRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMPLOYEE_RESTAURANT_IBFK_1, Keys.FKK3N4AQDUXDBJ5YBQLLJYP9ES7, Keys.EMPLOYEE_RESTAURANT_IBFK_2, Keys.FKMRRUKMHMYSLPV2QHF2BCWCGM6);
    }

    private transient EmployeePath _employeeRestaurantIbfk_1;

    /**
     * Get the implicit join path to the <code>test.employee</code> table, via
     * the <code>employee_restaurant_ibfk_1</code> key.
     */
    public EmployeePath employeeRestaurantIbfk_1() {
        if (_employeeRestaurantIbfk_1 == null)
            _employeeRestaurantIbfk_1 = new EmployeePath(this, Keys.EMPLOYEE_RESTAURANT_IBFK_1, null);

        return _employeeRestaurantIbfk_1;
    }

    private transient EmployeePath _fkk3n4aqduxdbj5ybqlljyp9es7;

    /**
     * Get the implicit join path to the <code>test.employee</code> table, via
     * the <code>FKk3n4aqduxdbj5ybqlljyp9es7</code> key.
     */
    public EmployeePath fkk3n4aqduxdbj5ybqlljyp9es7() {
        if (_fkk3n4aqduxdbj5ybqlljyp9es7 == null)
            _fkk3n4aqduxdbj5ybqlljyp9es7 = new EmployeePath(this, Keys.FKK3N4AQDUXDBJ5YBQLLJYP9ES7, null);

        return _fkk3n4aqduxdbj5ybqlljyp9es7;
    }

    private transient RestaurantPath _employeeRestaurantIbfk_2;

    /**
     * Get the implicit join path to the <code>test.restaurant</code> table, via
     * the <code>employee_restaurant_ibfk_2</code> key.
     */
    public RestaurantPath employeeRestaurantIbfk_2() {
        if (_employeeRestaurantIbfk_2 == null)
            _employeeRestaurantIbfk_2 = new RestaurantPath(this, Keys.EMPLOYEE_RESTAURANT_IBFK_2, null);

        return _employeeRestaurantIbfk_2;
    }

    private transient RestaurantPath _fkmrrukmhmyslpv2qhf2bcwcgm6;

    /**
     * Get the implicit join path to the <code>test.restaurant</code> table, via
     * the <code>FKmrrukmhmyslpv2qhf2bcwcgm6</code> key.
     */
    public RestaurantPath fkmrrukmhmyslpv2qhf2bcwcgm6() {
        if (_fkmrrukmhmyslpv2qhf2bcwcgm6 == null)
            _fkmrrukmhmyslpv2qhf2bcwcgm6 = new RestaurantPath(this, Keys.FKMRRUKMHMYSLPV2QHF2BCWCGM6, null);

        return _fkmrrukmhmyslpv2qhf2bcwcgm6;
    }

    @Override
    public EmployeeRestaurant as(String alias) {
        return new EmployeeRestaurant(DSL.name(alias), this);
    }

    @Override
    public EmployeeRestaurant as(Name alias) {
        return new EmployeeRestaurant(alias, this);
    }

    @Override
    public EmployeeRestaurant as(Table<?> alias) {
        return new EmployeeRestaurant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeRestaurant rename(String name) {
        return new EmployeeRestaurant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeRestaurant rename(Name name) {
        return new EmployeeRestaurant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeRestaurant rename(Table<?> name) {
        return new EmployeeRestaurant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant where(Condition condition) {
        return new EmployeeRestaurant(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeRestaurant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeRestaurant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeRestaurant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeRestaurant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeRestaurant whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
