/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.EmployeeRestaurant.EmployeeRestaurantPath;
import org.example.jooq.tables.Restaurant.RestaurantPath;
import org.example.jooq.tables.records.EmployeeRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Employee extends TableImpl<EmployeeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.employee</code>
     */
    public static final Employee EMPLOYEE = new Employee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeRecord> getRecordType() {
        return EmployeeRecord.class;
    }

    /**
     * The column <code>test.employee.employee_id</code>.
     */
    public final TableField<EmployeeRecord, Integer> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.employee.first_name</code>.
     */
    public final TableField<EmployeeRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.employee.last_name</code>.
     */
    public final TableField<EmployeeRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(255), this, "");

    private Employee(Name alias, Table<EmployeeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Employee(Name alias, Table<EmployeeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.employee</code> table reference
     */
    public Employee(String alias) {
        this(DSL.name(alias), EMPLOYEE);
    }

    /**
     * Create an aliased <code>test.employee</code> table reference
     */
    public Employee(Name alias) {
        this(alias, EMPLOYEE);
    }

    /**
     * Create a <code>test.employee</code> table reference
     */
    public Employee() {
        this(DSL.name("employee"), null);
    }

    public <O extends Record> Employee(Table<O> path, ForeignKey<O, EmployeeRecord> childPath, InverseForeignKey<O, EmployeeRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeePath extends Employee implements Path<EmployeeRecord> {
        public <O extends Record> EmployeePath(Table<O> path, ForeignKey<O, EmployeeRecord> childPath, InverseForeignKey<O, EmployeeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeePath(Name alias, Table<EmployeeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeePath as(String alias) {
            return new EmployeePath(DSL.name(alias), this);
        }

        @Override
        public EmployeePath as(Name alias) {
            return new EmployeePath(alias, this);
        }

        @Override
        public EmployeePath as(Table<?> alias) {
            return new EmployeePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public Identity<EmployeeRecord, Integer> getIdentity() {
        return (Identity<EmployeeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmployeeRecord> getPrimaryKey() {
        return Keys.KEY_EMPLOYEE_PRIMARY;
    }

    private transient EmployeeRestaurantPath _employeeRestaurantIbfk_1;

    /**
     * Get the implicit to-many join path to the
     * <code>test.employee_restaurant</code> table, via the
     * <code>employee_restaurant_ibfk_1</code> key
     */
    public EmployeeRestaurantPath employeeRestaurantIbfk_1() {
        if (_employeeRestaurantIbfk_1 == null)
            _employeeRestaurantIbfk_1 = new EmployeeRestaurantPath(this, null, Keys.EMPLOYEE_RESTAURANT_IBFK_1.getInverseKey());

        return _employeeRestaurantIbfk_1;
    }

    private transient EmployeeRestaurantPath _fkk3n4aqduxdbj5ybqlljyp9es7;

    /**
     * Get the implicit to-many join path to the
     * <code>test.employee_restaurant</code> table, via the
     * <code>FKk3n4aqduxdbj5ybqlljyp9es7</code> key
     */
    public EmployeeRestaurantPath fkk3n4aqduxdbj5ybqlljyp9es7() {
        if (_fkk3n4aqduxdbj5ybqlljyp9es7 == null)
            _fkk3n4aqduxdbj5ybqlljyp9es7 = new EmployeeRestaurantPath(this, null, Keys.FKK3N4AQDUXDBJ5YBQLLJYP9ES7.getInverseKey());

        return _fkk3n4aqduxdbj5ybqlljyp9es7;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>test.restaurant</code> table, via the
     * <code>employee_restaurant_ibfk_2</code> key
     */
    public RestaurantPath employeeRestaurantIbfk_2() {
        return employeeRestaurantIbfk_1().employeeRestaurantIbfk_2();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>test.restaurant</code> table, via the
     * <code>FKmrrukmhmyslpv2qhf2bcwcgm6</code> key
     */
    public RestaurantPath fkmrrukmhmyslpv2qhf2bcwcgm6() {
        return employeeRestaurantIbfk_1().fkmrrukmhmyslpv2qhf2bcwcgm6();
    }

    @Override
    public Employee as(String alias) {
        return new Employee(DSL.name(alias), this);
    }

    @Override
    public Employee as(Name alias) {
        return new Employee(alias, this);
    }

    @Override
    public Employee as(Table<?> alias) {
        return new Employee(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(String name) {
        return new Employee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(Name name) {
        return new Employee(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Employee rename(Table<?> name) {
        return new Employee(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Condition condition) {
        return new Employee(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Employee where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Employee whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
