/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Organization.OrganizationPath;
import org.example.jooq.tables.OrganizationMember.OrganizationMemberPath;
import org.example.jooq.tables.records.MemberRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Member extends TableImpl<MemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.Member</code>
     */
    public static final Member MEMBER = new Member();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberRecord> getRecordType() {
        return MemberRecord.class;
    }

    /**
     * The column <code>test.Member.id</code>.
     */
    public final TableField<MemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private Member(Name alias, Table<MemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Member(Name alias, Table<MemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.Member</code> table reference
     */
    public Member(String alias) {
        this(DSL.name(alias), MEMBER);
    }

    /**
     * Create an aliased <code>test.Member</code> table reference
     */
    public Member(Name alias) {
        this(alias, MEMBER);
    }

    /**
     * Create a <code>test.Member</code> table reference
     */
    public Member() {
        this(DSL.name("Member"), null);
    }

    public <O extends Record> Member(Table<O> path, ForeignKey<O, MemberRecord> childPath, InverseForeignKey<O, MemberRecord> parentPath) {
        super(path, childPath, parentPath, MEMBER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MemberPath extends Member implements Path<MemberRecord> {
        public <O extends Record> MemberPath(Table<O> path, ForeignKey<O, MemberRecord> childPath, InverseForeignKey<O, MemberRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MemberPath(Name alias, Table<MemberRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MemberPath as(String alias) {
            return new MemberPath(DSL.name(alias), this);
        }

        @Override
        public MemberPath as(Name alias) {
            return new MemberPath(alias, this);
        }

        @Override
        public MemberPath as(Table<?> alias) {
            return new MemberPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public Identity<MemberRecord, Long> getIdentity() {
        return (Identity<MemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MemberRecord> getPrimaryKey() {
        return Keys.KEY_MEMBER_PRIMARY;
    }

    private transient OrganizationMemberPath _organizationMember;

    /**
     * Get the implicit to-many join path to the
     * <code>test.Organization_Member</code> table
     */
    public OrganizationMemberPath organizationMember() {
        if (_organizationMember == null)
            _organizationMember = new OrganizationMemberPath(this, null, Keys.FK99B1072T8R62TWT7A8QRXAHT7.getInverseKey());

        return _organizationMember;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>test.Organization</code> table
     */
    public OrganizationPath organization() {
        return organizationMember().organization();
    }

    @Override
    public Member as(String alias) {
        return new Member(DSL.name(alias), this);
    }

    @Override
    public Member as(Name alias) {
        return new Member(alias, this);
    }

    @Override
    public Member as(Table<?> alias) {
        return new Member(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Member rename(String name) {
        return new Member(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Member rename(Name name) {
        return new Member(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Member rename(Table<?> name) {
        return new Member(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member where(Condition condition) {
        return new Member(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Member where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Member where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Member where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Member where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Member whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
