/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Member.MemberPath;
import org.example.jooq.tables.Organization.OrganizationPath;
import org.example.jooq.tables.records.OrganizationMemberRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrganizationMember extends TableImpl<OrganizationMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.Organization_Member</code>
     */
    public static final OrganizationMember ORGANIZATION_MEMBER = new OrganizationMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizationMemberRecord> getRecordType() {
        return OrganizationMemberRecord.class;
    }

    /**
     * The column <code>test.Organization_Member.Organization_id</code>.
     */
    public final TableField<OrganizationMemberRecord, Long> ORGANIZATION_ID = createField(DSL.name("Organization_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>test.Organization_Member.members_id</code>.
     */
    public final TableField<OrganizationMemberRecord, Long> MEMBERS_ID = createField(DSL.name("members_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private OrganizationMember(Name alias, Table<OrganizationMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrganizationMember(Name alias, Table<OrganizationMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.Organization_Member</code> table reference
     */
    public OrganizationMember(String alias) {
        this(DSL.name(alias), ORGANIZATION_MEMBER);
    }

    /**
     * Create an aliased <code>test.Organization_Member</code> table reference
     */
    public OrganizationMember(Name alias) {
        this(alias, ORGANIZATION_MEMBER);
    }

    /**
     * Create a <code>test.Organization_Member</code> table reference
     */
    public OrganizationMember() {
        this(DSL.name("Organization_Member"), null);
    }

    public <O extends Record> OrganizationMember(Table<O> path, ForeignKey<O, OrganizationMemberRecord> childPath, InverseForeignKey<O, OrganizationMemberRecord> parentPath) {
        super(path, childPath, parentPath, ORGANIZATION_MEMBER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganizationMemberPath extends OrganizationMember implements Path<OrganizationMemberRecord> {
        public <O extends Record> OrganizationMemberPath(Table<O> path, ForeignKey<O, OrganizationMemberRecord> childPath, InverseForeignKey<O, OrganizationMemberRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganizationMemberPath(Name alias, Table<OrganizationMemberRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganizationMemberPath as(String alias) {
            return new OrganizationMemberPath(DSL.name(alias), this);
        }

        @Override
        public OrganizationMemberPath as(Name alias) {
            return new OrganizationMemberPath(alias, this);
        }

        @Override
        public OrganizationMemberPath as(Table<?> alias) {
            return new OrganizationMemberPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public UniqueKey<OrganizationMemberRecord> getPrimaryKey() {
        return Keys.KEY_ORGANIZATION_MEMBER_PRIMARY;
    }

    @Override
    public List<ForeignKey<OrganizationMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK3OU05GN1LQHE1WJ992DNNCF3W, Keys.FK99B1072T8R62TWT7A8QRXAHT7);
    }

    private transient OrganizationPath _organization;

    /**
     * Get the implicit join path to the <code>test.Organization</code> table.
     */
    public OrganizationPath organization() {
        if (_organization == null)
            _organization = new OrganizationPath(this, Keys.FK3OU05GN1LQHE1WJ992DNNCF3W, null);

        return _organization;
    }

    private transient MemberPath _member;

    /**
     * Get the implicit join path to the <code>test.Member</code> table.
     */
    public MemberPath member() {
        if (_member == null)
            _member = new MemberPath(this, Keys.FK99B1072T8R62TWT7A8QRXAHT7, null);

        return _member;
    }

    @Override
    public OrganizationMember as(String alias) {
        return new OrganizationMember(DSL.name(alias), this);
    }

    @Override
    public OrganizationMember as(Name alias) {
        return new OrganizationMember(alias, this);
    }

    @Override
    public OrganizationMember as(Table<?> alias) {
        return new OrganizationMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationMember rename(String name) {
        return new OrganizationMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationMember rename(Name name) {
        return new OrganizationMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationMember rename(Table<?> name) {
        return new OrganizationMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember where(Condition condition) {
        return new OrganizationMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrganizationMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrganizationMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrganizationMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrganizationMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrganizationMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
