/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.Member.MemberPath;
import org.example.jooq.tables.OrganizationMember.OrganizationMemberPath;
import org.example.jooq.tables.records.OrganizationRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Organization extends TableImpl<OrganizationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.Organization</code>
     */
    public static final Organization ORGANIZATION = new Organization();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizationRecord> getRecordType() {
        return OrganizationRecord.class;
    }

    /**
     * The column <code>test.Organization.id</code>.
     */
    public final TableField<OrganizationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private Organization(Name alias, Table<OrganizationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Organization(Name alias, Table<OrganizationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.Organization</code> table reference
     */
    public Organization(String alias) {
        this(DSL.name(alias), ORGANIZATION);
    }

    /**
     * Create an aliased <code>test.Organization</code> table reference
     */
    public Organization(Name alias) {
        this(alias, ORGANIZATION);
    }

    /**
     * Create a <code>test.Organization</code> table reference
     */
    public Organization() {
        this(DSL.name("Organization"), null);
    }

    public <O extends Record> Organization(Table<O> path, ForeignKey<O, OrganizationRecord> childPath, InverseForeignKey<O, OrganizationRecord> parentPath) {
        super(path, childPath, parentPath, ORGANIZATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrganizationPath extends Organization implements Path<OrganizationRecord> {
        public <O extends Record> OrganizationPath(Table<O> path, ForeignKey<O, OrganizationRecord> childPath, InverseForeignKey<O, OrganizationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrganizationPath(Name alias, Table<OrganizationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrganizationPath as(String alias) {
            return new OrganizationPath(DSL.name(alias), this);
        }

        @Override
        public OrganizationPath as(Name alias) {
            return new OrganizationPath(alias, this);
        }

        @Override
        public OrganizationPath as(Table<?> alias) {
            return new OrganizationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public Identity<OrganizationRecord, Long> getIdentity() {
        return (Identity<OrganizationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganizationRecord> getPrimaryKey() {
        return Keys.KEY_ORGANIZATION_PRIMARY;
    }

    private transient OrganizationMemberPath _organizationMember;

    /**
     * Get the implicit to-many join path to the
     * <code>test.Organization_Member</code> table
     */
    public OrganizationMemberPath organizationMember() {
        if (_organizationMember == null)
            _organizationMember = new OrganizationMemberPath(this, null, Keys.FK3OU05GN1LQHE1WJ992DNNCF3W.getInverseKey());

        return _organizationMember;
    }

    /**
     * Get the implicit many-to-many join path to the <code>test.Member</code>
     * table
     */
    public MemberPath member() {
        return organizationMember().member();
    }

    @Override
    public Organization as(String alias) {
        return new Organization(DSL.name(alias), this);
    }

    @Override
    public Organization as(Name alias) {
        return new Organization(alias, this);
    }

    @Override
    public Organization as(Table<?> alias) {
        return new Organization(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organization rename(String name) {
        return new Organization(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organization rename(Name name) {
        return new Organization(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organization rename(Table<?> name) {
        return new Organization(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization where(Condition condition) {
        return new Organization(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organization where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organization where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organization where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Organization where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Organization whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
