/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.jooq.Indexes;
import org.example.jooq.Keys;
import org.example.jooq.Test;
import org.example.jooq.tables.City.CityPath;
import org.example.jooq.tables.Employee.EmployeePath;
import org.example.jooq.tables.EmployeeRestaurant.EmployeeRestaurantPath;
import org.example.jooq.tables.records.RestaurantRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Restaurant extends TableImpl<RestaurantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.restaurant</code>
     */
    public static final Restaurant RESTAURANT = new Restaurant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestaurantRecord> getRecordType() {
        return RestaurantRecord.class;
    }

    /**
     * The column <code>test.restaurant.restaurant_id</code>.
     */
    public final TableField<RestaurantRecord, Integer> RESTAURANT_ID = createField(DSL.name("restaurant_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.restaurant.name</code>.
     */
    public final TableField<RestaurantRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.restaurant.employee_count</code>.
     */
    public final TableField<RestaurantRecord, Integer> EMPLOYEE_COUNT = createField(DSL.name("employee_count"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.restaurant.rating</code>.
     */
    public final TableField<RestaurantRecord, BigDecimal> RATING = createField(DSL.name("rating"), SQLDataType.DECIMAL(2, 1), this, "");

    /**
     * The column <code>test.restaurant.city_id</code>.
     */
    public final TableField<RestaurantRecord, Integer> CITY_ID = createField(DSL.name("city_id"), SQLDataType.INTEGER, this, "");

    private Restaurant(Name alias, Table<RestaurantRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Restaurant(Name alias, Table<RestaurantRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.restaurant</code> table reference
     */
    public Restaurant(String alias) {
        this(DSL.name(alias), RESTAURANT);
    }

    /**
     * Create an aliased <code>test.restaurant</code> table reference
     */
    public Restaurant(Name alias) {
        this(alias, RESTAURANT);
    }

    /**
     * Create a <code>test.restaurant</code> table reference
     */
    public Restaurant() {
        this(DSL.name("restaurant"), null);
    }

    public <O extends Record> Restaurant(Table<O> path, ForeignKey<O, RestaurantRecord> childPath, InverseForeignKey<O, RestaurantRecord> parentPath) {
        super(path, childPath, parentPath, RESTAURANT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RestaurantPath extends Restaurant implements Path<RestaurantRecord> {
        public <O extends Record> RestaurantPath(Table<O> path, ForeignKey<O, RestaurantRecord> childPath, InverseForeignKey<O, RestaurantRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RestaurantPath(Name alias, Table<RestaurantRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RestaurantPath as(String alias) {
            return new RestaurantPath(DSL.name(alias), this);
        }

        @Override
        public RestaurantPath as(Name alias) {
            return new RestaurantPath(alias, this);
        }

        @Override
        public RestaurantPath as(Table<?> alias) {
            return new RestaurantPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RESTAURANT_CITY_ID);
    }

    @Override
    public Identity<RestaurantRecord, Integer> getIdentity() {
        return (Identity<RestaurantRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RestaurantRecord> getPrimaryKey() {
        return Keys.KEY_RESTAURANT_PRIMARY;
    }

    @Override
    public List<ForeignKey<RestaurantRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKL968D8D7966YYMVSXTDSNI1VW, Keys.RESTAURANT_IBFK_1);
    }

    private transient CityPath _fkl968d8d7966yymvsxtdsni1vw;

    /**
     * Get the implicit join path to the <code>test.city</code> table, via the
     * <code>FKl968d8d7966yymvsxtdsni1vw</code> key.
     */
    public CityPath fkl968d8d7966yymvsxtdsni1vw() {
        if (_fkl968d8d7966yymvsxtdsni1vw == null)
            _fkl968d8d7966yymvsxtdsni1vw = new CityPath(this, Keys.FKL968D8D7966YYMVSXTDSNI1VW, null);

        return _fkl968d8d7966yymvsxtdsni1vw;
    }

    private transient CityPath _restaurantIbfk_1;

    /**
     * Get the implicit join path to the <code>test.city</code> table, via the
     * <code>restaurant_ibfk_1</code> key.
     */
    public CityPath restaurantIbfk_1() {
        if (_restaurantIbfk_1 == null)
            _restaurantIbfk_1 = new CityPath(this, Keys.RESTAURANT_IBFK_1, null);

        return _restaurantIbfk_1;
    }

    private transient EmployeeRestaurantPath _employeeRestaurantIbfk_2;

    /**
     * Get the implicit to-many join path to the
     * <code>test.employee_restaurant</code> table, via the
     * <code>employee_restaurant_ibfk_2</code> key
     */
    public EmployeeRestaurantPath employeeRestaurantIbfk_2() {
        if (_employeeRestaurantIbfk_2 == null)
            _employeeRestaurantIbfk_2 = new EmployeeRestaurantPath(this, null, Keys.EMPLOYEE_RESTAURANT_IBFK_2.getInverseKey());

        return _employeeRestaurantIbfk_2;
    }

    private transient EmployeeRestaurantPath _fkmrrukmhmyslpv2qhf2bcwcgm6;

    /**
     * Get the implicit to-many join path to the
     * <code>test.employee_restaurant</code> table, via the
     * <code>FKmrrukmhmyslpv2qhf2bcwcgm6</code> key
     */
    public EmployeeRestaurantPath fkmrrukmhmyslpv2qhf2bcwcgm6() {
        if (_fkmrrukmhmyslpv2qhf2bcwcgm6 == null)
            _fkmrrukmhmyslpv2qhf2bcwcgm6 = new EmployeeRestaurantPath(this, null, Keys.FKMRRUKMHMYSLPV2QHF2BCWCGM6.getInverseKey());

        return _fkmrrukmhmyslpv2qhf2bcwcgm6;
    }

    /**
     * Get the implicit many-to-many join path to the <code>test.employee</code>
     * table, via the <code>employee_restaurant_ibfk_1</code> key
     */
    public EmployeePath employeeRestaurantIbfk_1() {
        return employeeRestaurantIbfk_2().employeeRestaurantIbfk_1();
    }

    /**
     * Get the implicit many-to-many join path to the <code>test.employee</code>
     * table, via the <code>FKk3n4aqduxdbj5ybqlljyp9es7</code> key
     */
    public EmployeePath fkk3n4aqduxdbj5ybqlljyp9es7() {
        return employeeRestaurantIbfk_2().fkk3n4aqduxdbj5ybqlljyp9es7();
    }

    @Override
    public List<Check<RestaurantRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("restaurant_chk_1"), "((`rating` >= 1) and (`rating` <= 5))", true)
        );
    }

    @Override
    public Restaurant as(String alias) {
        return new Restaurant(DSL.name(alias), this);
    }

    @Override
    public Restaurant as(Name alias) {
        return new Restaurant(alias, this);
    }

    @Override
    public Restaurant as(Table<?> alias) {
        return new Restaurant(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurant rename(String name) {
        return new Restaurant(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurant rename(Name name) {
        return new Restaurant(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurant rename(Table<?> name) {
        return new Restaurant(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant where(Condition condition) {
        return new Restaurant(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restaurant where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restaurant where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restaurant where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Restaurant where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Restaurant whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
