/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Test;
import org.example.jooq.tables.records.RestaurantEmployeeCountRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestaurantEmployeeCount extends TableImpl<RestaurantEmployeeCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.restaurant_employee_count</code>
     */
    public static final RestaurantEmployeeCount RESTAURANT_EMPLOYEE_COUNT = new RestaurantEmployeeCount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestaurantEmployeeCountRecord> getRecordType() {
        return RestaurantEmployeeCountRecord.class;
    }

    /**
     * The column <code>test.restaurant_employee_count.Restaurang</code>.
     */
    public final TableField<RestaurantEmployeeCountRecord, String> RESTAURANG = createField(DSL.name("Restaurang"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.restaurant_employee_count.Antal Anställda</code>.
     */
    public final TableField<RestaurantEmployeeCountRecord, Long> ANTAL_ANSTÄLLDA = createField(DSL.name("Antal Anställda"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private RestaurantEmployeeCount(Name alias, Table<RestaurantEmployeeCountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RestaurantEmployeeCount(Name alias, Table<RestaurantEmployeeCountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `restaurant_employee_count` as select `r`.`name` AS `Restaurang`,count(`er`.`employee_id`) AS `Antal Anställda` from (`test`.`restaurant` `r` join `test`.`employee_restaurant` `er` on((`r`.`restaurant_id` = `er`.`restaurant_id`))) group by `r`.`name`"), where);
    }

    /**
     * Create an aliased <code>test.restaurant_employee_count</code> table
     * reference
     */
    public RestaurantEmployeeCount(String alias) {
        this(DSL.name(alias), RESTAURANT_EMPLOYEE_COUNT);
    }

    /**
     * Create an aliased <code>test.restaurant_employee_count</code> table
     * reference
     */
    public RestaurantEmployeeCount(Name alias) {
        this(alias, RESTAURANT_EMPLOYEE_COUNT);
    }

    /**
     * Create a <code>test.restaurant_employee_count</code> table reference
     */
    public RestaurantEmployeeCount() {
        this(DSL.name("restaurant_employee_count"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public RestaurantEmployeeCount as(String alias) {
        return new RestaurantEmployeeCount(DSL.name(alias), this);
    }

    @Override
    public RestaurantEmployeeCount as(Name alias) {
        return new RestaurantEmployeeCount(alias, this);
    }

    @Override
    public RestaurantEmployeeCount as(Table<?> alias) {
        return new RestaurantEmployeeCount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RestaurantEmployeeCount rename(String name) {
        return new RestaurantEmployeeCount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RestaurantEmployeeCount rename(Name name) {
        return new RestaurantEmployeeCount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RestaurantEmployeeCount rename(Table<?> name) {
        return new RestaurantEmployeeCount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount where(Condition condition) {
        return new RestaurantEmployeeCount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestaurantEmployeeCount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestaurantEmployeeCount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestaurantEmployeeCount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestaurantEmployeeCount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestaurantEmployeeCount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
