/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.util.Collection;

import org.example.jooq.Test;
import org.example.jooq.tables.records.TableNameRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TableName extends TableImpl<TableNameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.table_name</code>
     */
    public static final TableName TABLE_NAME = new TableName();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TableNameRecord> getRecordType() {
        return TableNameRecord.class;
    }

    /**
     * The column <code>test.table_name.column_name</code>.
     */
    public final TableField<TableNameRecord, Integer> COLUMN_NAME = createField(DSL.name("column_name"), SQLDataType.INTEGER, this, "");

    private TableName(Name alias, Table<TableNameRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TableName(Name alias, Table<TableNameRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test.table_name</code> table reference
     */
    public TableName(String alias) {
        this(DSL.name(alias), TABLE_NAME);
    }

    /**
     * Create an aliased <code>test.table_name</code> table reference
     */
    public TableName(Name alias) {
        this(alias, TABLE_NAME);
    }

    /**
     * Create a <code>test.table_name</code> table reference
     */
    public TableName() {
        this(DSL.name("table_name"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public TableName as(String alias) {
        return new TableName(DSL.name(alias), this);
    }

    @Override
    public TableName as(Name alias) {
        return new TableName(alias, this);
    }

    @Override
    public TableName as(Table<?> alias) {
        return new TableName(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TableName rename(String name) {
        return new TableName(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableName rename(Name name) {
        return new TableName(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableName rename(Table<?> name) {
        return new TableName(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName where(Condition condition) {
        return new TableName(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TableName where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TableName where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TableName where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TableName where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TableName whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
